openapi: 3.0.3
info:
  title: Autograder API
  description: API for managing and running autograder tests.
  version: 1.2.1
servers:
  - url: https://nonedified-andreas-degradedly.ngrok-free.app/api
    description: Ngrok Tunnel
  - url: http://dl-berlin.ecn.purdue.edu/api
    description: Frontend Proxy
  - url: http://dl-berlin.ecn.purdue.edu:8000
    description: Direct Backend Server
paths:
  /register:
    post:
      summary: Register a team
      description: Register a team with the server.
      operationId: registerTeam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                group:
                  type: integer
                  description: The group number.
                github:
                  type: string
                  description: GitHub repository URL.
                  format: uri
                endpoint:
                  type: string
                  description: Link to your hosted endpoint on AWS.
                  format: uri
                fe_endpoint:
                  type: string
                  description: Link to your Frontend hosted endpoint.
                  format: uri
                gh_token:
                  type: string
                  description: GitHub authentication token.
                names:
                  type: array
                  items:
                    type: string
                  description: Names of the team members.
              required:
                - group
                - github
                - gh_token
                - names
                - endpoint
                - fe_endpoint
      responses:
        '201':
          description: Team registered successfully.
        '400':
          description: Invalid input data.
        '403':
          description: Unauthorized.

  /schedule:
    get:
      summary: Get current scheduled runs
      description: Get a list of all currently scheduled runs in the queue
      operationId: getScheduledRun
      responses:
        '202':
          description: Returned Listed sucessfully.

    post:
      summary: Schedule a run
      description: Schedule a new test run for the specified group.
      operationId: scheduleRun
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                group:
                  type: integer
                  description: The group number.
                gh_token:
                  type: string
                  description: GitHub authentication token.
              required:
                - group
                - gh_token
      responses:
        '202':
          description: Run scheduled successfully.
        '400':
          description: Invalid input data.

  /run/all:
    get:
      summary: Get currently running + scheduled runs
      description: Retrieve list of all running and scheduled tasks
      operationId: getRunAll

      responses:
        '200':
          description: List of all the scheduled tasks.

  /last_run:
    get:
      summary: Check results from the last run
      description: Retrieve results of the most recent test run.
      operationId: getLastRun
      parameters:
        - name: group
          in: query
          description: The group number.
          required: true
          schema:
            type: integer
        - name: gh_token
          in: query
          description: GitHub authentication token.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Results from the last run retrieved successfully.
        '400':
          description: Invalid input data.

  /best_run:
    get:
      summary: Check results from the best run
      description: Retrieve results of the best test run.
      operationId: getBestRun
      parameters:
        - name: group
          in: query
          description: The group number.
          required: true
          schema:
            type: integer
        - name: gh_token
          in: query
          description: GitHub authentication token.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Results from the best run retrieved successfully.
        '400':
          description: Invalid input data.

  /log/download:
    get:
      summary: Download a log file
      description: Retrieve a specific log file for detailed analysis.
      operationId: downloadLog
      parameters:
        - name: group
          in: query
          description: The group number.
          required: true
          schema:
            type: integer
        - name: gh_token
          in: query
          description: GitHub authentication token.
          required: true
          schema:
            type: string
        - name: log
          in: query
          description: path of the log file
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Log file downloaded successfully.
        '400':
          description: Invalid input data.



  /stats:
    get:
      summary: Get current stats of the class
      description: Return the average, max, median, min, std_dev
      operationId: seeStats
      parameters:
        - name: gh_token
          in: query
          description: GitHub authentication token.
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Stats shown successfully.

