name: CD (main)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cd-main
  cancel-in-progress: false

env:
  TF_DIR: infra/envs/dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_CLI_ARGS: "-lock-timeout=5m"
      TF_VAR_aws_region: us-east-1

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # aws-session-token:   ${{ secrets.AWS_SESSION_TOKEN }}   # if using temp creds

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -input=false

      - name: Select/Create Workspace (dev)
        working-directory: ${{ env.TF_DIR }}
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve tfplan

      - name: Read validator URL
        id: tfout
        working-directory: ${{ env.TF_DIR }}
        run: echo "validator_url=$(terraform output -raw validator_service_url)" >> $GITHUB_OUTPUT

      - name: Smoke check /health
        run: |
          URL="${{ steps.tfout.outputs.validator_url }}/health"
          echo "Checking $URL ..."
          for i in {1..20}; do
            curl -fsS "$URL" && exit 0
            sleep 5
          done
          echo "Health check failed" && exit 1
