name: Add Copilot Reviewer

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
permissions:
  pull-requests: write
jobs:
  add-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Add Copilot reviewer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh api \
            -X POST \
            repos/$REPO/pulls/$PR_NUMBER/requested_reviewers \
            -f reviewers='["github-copilot"]'
